"use client"

import { Fragment, useState } from "react"
import { useQuery } from "@tanstack/react-query"
import { CalendarClock, Sparkles, ChevronDown, Loader2, AlertTriangle } from "lucide-react"
import { apiPost, formatCurrency, formatNumber } from "@/lib/api"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Skeleton } from "@/components/ui/skeleton"
import { AnalysisMarkdown } from "@/components/analysis-markdown"
import { cn } from "@/lib/utils"

type ConsultRow = {
  dealId: string
  dealName: string
  pipeline: string
  stage: string
  territory: string
  amount: number
  meetingDate: string
  daysElapsed: number
}
type RepGroup = { rep: string; count: number; amount: number; deals: ConsultRow[] }

export type ConsultNoQuoteData = {
  dateFrom?: string
  dateTo?: string
  totalConsults: number
  totalAmount: number
  byRep: RepGroup[]
  error?: string
}

type AnalysisResponse = {
  deal: { id: string; name: string; stage: string; pipeline: string; amount: number; ownerName: string; ageDays: number | null }
  engagementCounts: { emails: number; calls: number; notes: number; meetings: number; tasks: number }
  totalEngagements: number
  analysisText: string
  error?: string
}

function fmtDate(iso: string): string {
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return "—"
  return d.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })
}

// Inline AI summary + evaluation for one consultation's deal. Fetches on mount
// (only mounted when its row is expanded) and shares the ["deal-analysis", id]
// query cache with the Funnel-page dialog so re-opening is instant.
function DealAnalysisPanel({ dealId }: { dealId: string }) {
  const { data, isLoading, error } = useQuery({
    queryKey: ["deal-analysis", dealId],
    queryFn: () => apiPost<AnalysisResponse>("/api/hs/deal-analysis", { dealId }),
    staleTime: 5 * 60_000,
    retry: false,
  })

  if (isLoading) {
    return (
      <div className="flex items-center gap-2 py-6 text-sm text-muted-foreground">
        <Loader2 className="size-4 animate-spin text-primary" aria-hidden />
        Reading the deal and its communication history…
      </div>
    )
  }
  if (error || data?.error) {
    return (
      <div className="flex items-start gap-2 rounded-md border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">
        <AlertTriangle className="mt-0.5 size-4 shrink-0" aria-hidden />
        <span>{data?.error || (error as Error)?.message || "Failed to analyze this deal."}</span>
      </div>
    )
  }
  if (!data) return null

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-wrap items-center gap-2 text-xs">
        <span className="rounded-md border bg-background px-2 py-1 font-medium">{data.deal.stage}</span>
        <span className="rounded-md border bg-background px-2 py-1 tabular-nums">
          {data.deal.amount > 0 ? formatCurrency(data.deal.amount) : "No amount"}
        </span>
        {data.deal.ageDays != null && (
          <span className="rounded-md border bg-background px-2 py-1 tabular-nums">{data.deal.ageDays}d old</span>
        )}
        <span className="rounded-md border bg-background px-2 py-1 tabular-nums">{data.deal.ownerName}</span>
      </div>
      <p className="text-xs text-muted-foreground">
        {data.totalEngagements} logged interaction{data.totalEngagements === 1 ? "" : "s"} · {data.engagementCounts.emails} emails ·{" "}
        {data.engagementCounts.calls} calls · {data.engagementCounts.meetings} meetings · {data.engagementCounts.notes} notes ·{" "}
        {data.engagementCounts.tasks} tasks
      </p>
      <AnalysisMarkdown text={data.analysisText} />
      <p className="text-[0.7rem] text-muted-foreground">Generated by AI from HubSpot deal data. Review before acting.</p>
    </div>
  )
}

// Consultations that happened 1+ days ago whose associated deal has NOT yet
// reached the Quoted stage — a follow-up / accountability list. Grouped by the
// meeting attendee (the rep who ran the consult); each rep's deals are sorted by
// days elapsed since the consultation, smallest to largest. Prop-driven from the
// nightly Sales Manager snapshot. Each row expands to an on-demand AI review.
export function ConsultNoQuoteSection({ data, loading }: { data: ConsultNoQuoteData | null; loading: boolean }) {
  const byRep = data?.byRep ?? []
  const [expanded, setExpanded] = useState<Set<string>>(new Set())
  const toggle = (id: string) =>
    setExpanded((prev) => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })

  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="text-base">
          Consultations awaiting a quote
          <span className="ml-2 text-sm font-normal text-muted-foreground">
            consultations 1+ days ago whose deal hasn&apos;t been quoted yet, by rep · expand a row for an AI review
          </span>
        </CardTitle>
      </CardHeader>
      <CardContent>
        {data?.error ? (
          <div className="py-2 text-sm text-destructive">{data.error || "Failed to load consultations."}</div>
        ) : loading ? (
          <div className="flex flex-col gap-3">
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Loader2 className="size-4 animate-spin" aria-hidden />
              Loading consultations…
            </div>
            {[0, 1, 2].map((i) => (
              <Skeleton key={i} className="h-24 w-full" />
            ))}
          </div>
        ) : byRep.length === 0 ? (
          <div className="py-6 text-center text-sm text-muted-foreground">
            No open consultations awaiting a quote. Every consultation from the last 90 days has an associated quote.
          </div>
        ) : (
          <div className="flex flex-col gap-5">
            {/* Totals strip */}
            <div className="flex flex-wrap gap-6 rounded-lg border bg-muted/30 p-4">
              <div>
                <div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                  Deals awaiting a quote
                </div>
                <div className="mt-1 num text-2xl font-bold">{formatNumber(data?.totalConsults ?? 0)}</div>
              </div>
              <div className="border-l pl-6">
                <div className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Sales reps</div>
                <div className="mt-1 num text-2xl font-bold">{formatNumber(byRep.length)}</div>
              </div>
            </div>

            {byRep.map((g) => (
              <div key={g.rep} className="overflow-hidden rounded-lg border">
                <div className="flex items-center justify-between gap-3 border-b bg-muted/40 px-4 py-2.5">
                  <div className="flex items-center gap-2">
                    <CalendarClock className="size-4 text-muted-foreground" aria-hidden />
                    <span className="font-semibold">{g.rep}</span>
                  </div>
                  <span className="text-xs text-muted-foreground">
                    {formatNumber(g.count)} {g.count === 1 ? "deal" : "deals"}
                  </span>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full min-w-[820px] border-collapse text-sm">
                    <thead>
                      <tr className="border-b text-xs uppercase tracking-wide text-muted-foreground">
                        <th className="px-4 py-2 text-left font-medium">Deal</th>
                        <th className="px-4 py-2 text-left font-medium">Stage</th>
                        <th className="px-4 py-2 text-left font-medium">Territory</th>
                        <th className="px-4 py-2 text-left font-medium">Consulted</th>
                        <th className="px-4 py-2 text-right font-medium">Days elapsed</th>
                        <th className="px-4 py-2 text-right font-medium">Amount</th>
                        <th className="px-4 py-2 text-right font-medium">AI review</th>
                      </tr>
                    </thead>
                    <tbody>
                      {g.deals.map((d) => {
                        const isOpen = expanded.has(d.dealId)
                        return (
                          <Fragment key={d.dealId}>
                            <tr
                              className={cn(
                                "cursor-pointer border-b last:border-0 hover:bg-muted/30",
                                isOpen && "bg-muted/30",
                              )}
                              onClick={() => toggle(d.dealId)}
                            >
                              <td className="max-w-[240px] truncate px-4 py-2 font-medium" title={d.dealName}>
                                {d.dealName}
                              </td>
                              <td className="px-4 py-2">
                                <span className="inline-block rounded-full border bg-muted/50 px-2 py-0.5 text-xs font-medium text-foreground">
                                  {d.stage || "—"}
                                </span>
                              </td>
                              <td className="px-4 py-2 text-muted-foreground">
                                {d.territory && d.territory !== "Unmapped" ? d.territory : "—"}
                              </td>
                              <td className="px-4 py-2 text-muted-foreground tabular-nums">{fmtDate(d.meetingDate)}</td>
                              <td className="px-4 py-2 text-right tabular-nums font-semibold">
                                {formatNumber(d.daysElapsed)}
                              </td>
                              <td className="px-4 py-2 text-right tabular-nums text-muted-foreground">
                                {d.amount > 0 ? formatCurrency(d.amount) : "—"}
                              </td>
                              <td className="px-4 py-2 text-right">
                                <span
                                  className="inline-flex items-center gap-1 rounded-md border border-primary/30 bg-primary/5 px-2 py-1 text-xs font-medium text-primary"
                                  aria-label={`${isOpen ? "Hide" : "Show"} AI review for ${d.dealName}`}
                                >
                                  <Sparkles className="size-3.5" aria-hidden />
                                  {isOpen ? "Hide" : "Analyze"}
                                  <ChevronDown
                                    className={cn("size-3.5 transition-transform", isOpen && "rotate-180")}
                                    aria-hidden
                                  />
                                </span>
                              </td>
                            </tr>
                            {isOpen && (
                              <tr className="border-b last:border-0 bg-muted/10">
                                <td colSpan={7} className="px-4 py-4">
                                  <DealAnalysisPanel dealId={d.dealId} />
                                </td>
                              </tr>
                            )}
                          </Fragment>
                        )
                      })}
                    </tbody>
                  </table>
                </div>
              </div>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  )
}
