"use client"

import { useMemo } from "react"
import { useQuery } from "@tanstack/react-query"
import { apiGet, apiPost, formatCurrency, formatNumber } from "@/lib/api"
import type { AdSpendRow } from "@/data/advertising-data"
import { Card } from "@/components/ui/card"
import { Skeleton } from "@/components/ui/skeleton"
import { Button } from "@/components/ui/button"
import { Download } from "lucide-react"

type LtvRow = {
  month: string
  contactsCreated: number
  revenue: number
  wonDeals: number
  ltv: number
}

type LtvResponse = {
  rows: LtvRow[]
  totals: { contactsCreated: number; revenue: number; wonDeals: number; ltv: number }
  attributedRevenue: number
  unattributedRevenue: number
  wonDealCount: number
}

// Currency with cents (formatCurrency rounds to whole dollars; LTV needs cents).
function money2(n: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(n || 0)
}

// "2023-01" -> "Jan 2023"
const MONTH_ABBR = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
function monthLabel(key: string): string {
  const [y, m] = key.split("-").map(Number)
  return `${MONTH_ABBR[m - 1]} ${y}`
}

export function ContactLtvCard({ configured }: { configured: boolean }) {
  const query = useQuery({
    queryKey: ["contact-ltv"],
    queryFn: () => apiPost<LtvResponse>("/api/hs/contact-ltv"),
    enabled: configured,
    staleTime: 5 * 60 * 1000,
  })

  // Monthly advertising spend (same source as the Advertising page). Used to
  // show ad expense, ad cost per won deal, and ad spend as % of revenue per cohort.
  const adQuery = useQuery({
    queryKey: ["advertising-spend"],
    queryFn: () => apiGet<{ rows: AdSpendRow[] }>("/api/advertising"),
    enabled: configured,
    staleTime: 5 * 60 * 1000,
  })

  const rows = query.data?.rows ?? []
  const totals = query.data?.totals

  // month ("YYYY-MM") -> total advertising spend that month.
  const spendByMonth = useMemo(() => {
    const map = new Map<string, number>()
    for (const r of adQuery.data?.rows ?? []) {
      map.set(r.month, (r.digital || 0) + (r.television || 0) + (r.print || 0))
    }
    return map
  }, [adQuery.data])

  // Total ad spend across only the cohort months present in the LTV table, so
  // the footer's per-deal / %-of-revenue math lines up with the visible rows.
  const totalAdSpend = useMemo(
    () => rows.reduce((sum, r) => sum + (spendByMonth.get(r.month) ?? 0), 0),
    [rows, spendByMonth],
  )

  const maxLtv = useMemo(() => rows.reduce((m, r) => Math.max(m, r.ltv), 0), [rows])

  const exportCsv = () => {
    if (!rows.length) return
    const header = [
      "Cohort month",
      "Contacts created",
      "Won deals",
      "Attributed revenue",
      "Revenue per won deal",
      "Ad expense",
      "Ad cost per won deal",
      "Ad % of revenue",
      "LTV per contact",
    ]
    const perWon = (rev: number, won: number) => (won > 0 ? (rev / won).toFixed(2) : "")
    const pctOfRev = (spend: number, rev: number) => (spend > 0 && rev > 0 ? ((spend / rev) * 100).toFixed(1) : "")
    const lines = rows.map((r) => {
      const adSpend = spendByMonth.get(r.month) ?? 0
      return [
        r.month,
        r.contactsCreated,
        r.wonDeals,
        r.revenue.toFixed(2),
        perWon(r.revenue, r.wonDeals),
        adSpend > 0 ? adSpend.toFixed(2) : "",
        perWon(adSpend, r.wonDeals),
        pctOfRev(adSpend, r.revenue),
        r.ltv.toFixed(2),
      ].join(",")
    })
    if (totals) {
      lines.push(
        [
          "TOTAL",
          totals.contactsCreated,
          totals.wonDeals,
          totals.revenue.toFixed(2),
          perWon(totals.revenue, totals.wonDeals),
          totalAdSpend > 0 ? totalAdSpend.toFixed(2) : "",
          perWon(totalAdSpend, totals.wonDeals),
          pctOfRev(totalAdSpend, totals.revenue),
          totals.ltv.toFixed(2),
        ].join(","),
      )
    }
    const blob = new Blob([[header.join(","), ...lines].join("\n")], { type: "text/csv" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = "contact-ltv-by-cohort.csv"
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <Card className="flex flex-col gap-4 p-5">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h3 className="text-base font-semibold text-foreground">Contact lifetime value by cohort</h3>
          <p className="mt-1 max-w-2xl text-xs text-muted-foreground">
            Each row is the universe of contacts created that month. Revenue looks forward across all time:
            the won revenue generated by those contacts (attributed to a contact&apos;s creation month via its
            associated deals), regardless of when the deal closed. LTV = attributed revenue &divide; contacts
            created that month. Recent cohorts read lower because they have had less time to mature.
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={exportCsv}
          disabled={!rows.length}
          className="shrink-0 gap-2 bg-transparent"
        >
          <Download className="h-4 w-4" />
          Export CSV
        </Button>
      </div>

      {query.isError ? (
        <p className="py-6 text-center text-sm text-destructive">
          Could not load lifetime-value data. {(query.error as Error)?.message}
        </p>
      ) : query.isLoading ? (
        <div className="flex flex-col gap-2">
          {Array.from({ length: 8 }).map((_, i) => (
            <Skeleton key={i} className="h-8 w-full" />
          ))}
        </div>
      ) : (
        <div className="max-h-[520px] overflow-auto rounded-md border border-border">
          <table className="w-full text-sm">
            <thead className="sticky top-0 z-10 bg-muted text-xs uppercase tracking-wide text-muted-foreground">
              <tr>
                <th className="px-3 py-2 text-left font-semibold">Cohort month</th>
                <th className="px-3 py-2 text-right font-semibold">Contacts created</th>
                <th className="px-3 py-2 text-right font-semibold">Won deals</th>
                <th className="px-3 py-2 text-right font-semibold">Attributed revenue</th>
                <th className="px-3 py-2 text-right font-semibold">Revenue / won deal</th>
                <th className="px-3 py-2 text-right font-semibold">Ad expense</th>
                <th className="px-3 py-2 text-right font-semibold">Ad cost / won deal</th>
                <th className="px-3 py-2 text-right font-semibold">Ad % of revenue</th>
                <th className="px-3 py-2 text-right font-semibold">LTV / contact</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {rows.map((r) => (
                <tr key={r.month} className="hover:bg-muted/40">
                  <td className="whitespace-nowrap px-3 py-2 font-medium">{monthLabel(r.month)}</td>
                  <td className="px-3 py-2 text-right tabular-nums">{formatNumber(r.contactsCreated)}</td>
                  <td className="px-3 py-2 text-right tabular-nums">{formatNumber(r.wonDeals)}</td>
                  <td className="px-3 py-2 text-right tabular-nums">{formatCurrency(r.revenue)}</td>
                  <td className="px-3 py-2 text-right tabular-nums">
                    {r.wonDeals > 0 ? money2(r.revenue / r.wonDeals) : "—"}
                  </td>
                  {(() => {
                    const adSpend = spendByMonth.get(r.month) ?? 0
                    return (
                      <>
                        <td className="px-3 py-2 text-right tabular-nums">
                          {adSpend > 0 ? formatCurrency(adSpend) : "—"}
                        </td>
                        <td className="px-3 py-2 text-right tabular-nums">
                          {adSpend > 0 && r.wonDeals > 0 ? money2(adSpend / r.wonDeals) : "—"}
                        </td>
                        <td className="px-3 py-2 text-right tabular-nums">
                          {adSpend > 0 && r.revenue > 0 ? `${((adSpend / r.revenue) * 100).toFixed(1)}%` : "—"}
                        </td>
                      </>
                    )
                  })()}
                  <td className="px-3 py-2">
                    <div className="flex items-center justify-end gap-2">
                      <div className="h-1.5 w-20 overflow-hidden rounded-full bg-muted">
                        <div
                          className="h-full rounded-full bg-primary"
                          style={{ width: `${maxLtv > 0 ? (r.ltv / maxLtv) * 100 : 0}%` }}
                        />
                      </div>
                      <span className="w-20 text-right font-semibold tabular-nums">{money2(r.ltv)}</span>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
            {totals ? (
              <tfoot className="sticky bottom-0 z-10 bg-muted font-semibold">
                <tr>
                  <td className="px-3 py-2 text-left">All cohorts</td>
                  <td className="px-3 py-2 text-right tabular-nums">{formatNumber(totals.contactsCreated)}</td>
                  <td className="px-3 py-2 text-right tabular-nums">{formatNumber(totals.wonDeals)}</td>
                  <td className="px-3 py-2 text-right tabular-nums">{formatCurrency(totals.revenue)}</td>
                  <td className="px-3 py-2 text-right tabular-nums">
                    {totals.wonDeals > 0 ? money2(totals.revenue / totals.wonDeals) : "—"}
                  </td>
                  <td className="px-3 py-2 text-right tabular-nums">
                    {totalAdSpend > 0 ? formatCurrency(totalAdSpend) : "—"}
                  </td>
                  <td className="px-3 py-2 text-right tabular-nums">
                    {totalAdSpend > 0 && totals.wonDeals > 0 ? money2(totalAdSpend / totals.wonDeals) : "—"}
                  </td>
                  <td className="px-3 py-2 text-right tabular-nums">
                    {totalAdSpend > 0 && totals.revenue > 0
                      ? `${((totalAdSpend / totals.revenue) * 100).toFixed(1)}%`
                      : "—"}
                  </td>
                  <td className="px-3 py-2 text-right tabular-nums">{money2(totals.ltv)}</td>
                </tr>
              </tfoot>
            ) : null}
          </table>
        </div>
      )}

      {query.data ? (
        <p className="text-xs text-muted-foreground">
          {formatCurrency(query.data.attributedRevenue)} of won revenue is attributed to {formatNumber(rows.length)}{" "}
          monthly cohorts from {rows[0] ? monthLabel(rows[0].month) : ""} forward.{" "}
          {formatCurrency(query.data.unattributedRevenue)} is excluded (won deals with no associated contact, or a
          contact created before the first cohort month).
        </p>
      ) : null}
    </Card>
  )
}
