"use client"

import { useQuery } from "@tanstack/react-query"
import { Sparkles, Loader2, AlertTriangle } from "lucide-react"
import { apiPost, formatCurrency } from "@/lib/api"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog"
import { AnalysisMarkdown } from "@/components/analysis-markdown"

type AnalysisResponse = {
  deal: { id: string; name: string; stage: string; pipeline: string; amount: number; ownerName: string; ageDays: number | null }
  engagementCounts: { emails: number; calls: number; notes: number; meetings: number; tasks: number }
  totalEngagements: number
  analysisText: string
  error?: string
}

export function DealAnalysisDialog({
  dealId,
  dealName,
  open,
  onOpenChange,
}: {
  dealId: string | null
  dealName: string | null
  open: boolean
  onOpenChange: (v: boolean) => void
}) {
  const { data, isLoading, error } = useQuery({
    queryKey: ["deal-analysis", dealId],
    queryFn: () => apiPost<AnalysisResponse>("/api/hs/deal-analysis", { dealId }),
    enabled: open && !!dealId,
    staleTime: 5 * 60_000,
    retry: false,
  })

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[85vh] max-w-2xl overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="size-4 text-primary" aria-hidden />
            AI deal analysis
          </DialogTitle>
          <DialogDescription className="truncate" title={dealName ?? undefined}>
            {dealName ?? "Deal"}
          </DialogDescription>
        </DialogHeader>

        {isLoading ? (
          <div className="flex flex-col items-center justify-center gap-3 py-12 text-sm text-muted-foreground">
            <Loader2 className="size-6 animate-spin text-primary" aria-hidden />
            Reading the deal and its communication history…
          </div>
        ) : error || data?.error ? (
          <div className="flex items-start gap-2 rounded-md border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">
            <AlertTriangle className="mt-0.5 size-4 shrink-0" aria-hidden />
            <span>{data?.error || (error as Error)?.message || "Failed to analyze this deal."}</span>
          </div>
        ) : data ? (
          <div className="flex flex-col gap-4">
            {/* Deal facts */}
            <div className="flex flex-wrap items-center gap-2 text-xs">
              <span className="rounded-md border bg-muted px-2 py-1 font-medium">{data.deal.stage}</span>
              <span className="rounded-md border bg-muted px-2 py-1 tabular-nums">
                {data.deal.amount > 0 ? formatCurrency(data.deal.amount) : "No amount"}
              </span>
              {data.deal.ageDays != null && (
                <span className="rounded-md border bg-muted px-2 py-1 tabular-nums">{data.deal.ageDays}d old</span>
              )}
              <span className="rounded-md border bg-muted px-2 py-1 tabular-nums">{data.deal.ownerName}</span>
            </div>

            <p className="text-xs text-muted-foreground">
              {data.totalEngagements} logged interaction{data.totalEngagements === 1 ? "" : "s"} · {data.engagementCounts.emails} emails · {data.engagementCounts.calls} calls · {data.engagementCounts.meetings} meetings · {data.engagementCounts.notes} notes · {data.engagementCounts.tasks} tasks
            </p>

            <AnalysisMarkdown text={data.analysisText} />

            <p className="text-[0.7rem] text-muted-foreground">
              Generated by AI from HubSpot deal data. Review before acting.
            </p>
          </div>
        ) : null}
      </DialogContent>
    </Dialog>
  )
}


